---
- hosts: web
  become: yes
  tasks:
  - name: install Apache
    yum: name=httpd state=present
  - name: install httpd tools
    yum: name=httpd-tools state=present
  - name: install git
    yum: name=git state=present
  - name: install jdk
    yum: name=java-1.8.0-openjdk.x86_64 state=present
  - name: install maven
    yum: name=maven.noarch state=present
